title: Box Critters Modding Community
description: |
  Install mods and other add-ons to Box Critters
base-url: ""
url: https://boxcrittersmods.ga
repository: boxcritters/boxcrittersmods.ga
bc-mod-api: api.boxcrittersmods.ga
show-mod-versions: true
collections:
  lists:
    output: true
    permalink: /:name/
  mods:
    output: true
    home: true
    title: Mods
    singular: Mod
  texturepacks:
    output: true
    home: true
    title: Texture Packs
    singular: Texture Pack
  shaders:
    output: true
    home: true
    title: Shaders
    singular: Shader
  projects:
    output: true
    home: false
    title: Projects
    singular: Project
  servers:
    output: true
    home: false
    title: Servers
    singular: Server
  authors:
    output: true
    home: false
    title: Authors
    singular: Author
  posts:
    output: true
    home: false
    title: Blog
    singular: Post
  other:
    output: true
    home: false
    title: Other
    singular: Other
permalink: pretty
production: true
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-avatar
  - jemoji
  - jekyll-mention
markdown: kramdown
theme: minima
kramdown:
  math-engine: mathjax
  auto_ids: false
  input: GFM
  entity-output: as_char
  footnote-nr: "1"
  toc-levels: 1..6
  gfm-quirks: paragraph_end
  syntax-highlighter-opts:
    default-lang: plaintext
  syntax-highlighter: rouge
  smart-quotes: lsquo,rsquo,ldquo,rdquo
excludes:
  - lib
  - Gemfile
  - Gemfile.lock
  - node_modules
  - bower.json
  - "*.sh"
  - README.md
  - gulffile.js
  - package.json
  - vendor
  - .gitignore
  - CNAME
  - icomoon-selection.json
defaults:
  - scope:
      path: ""
    values:
      featured: false
      layout: listing-page
      list: false
      show-nav: false
  - scope:
      path: ""
      type: lists
    values:
      layout: list-page
  - scope:
      path: ""
      type: mods
    values:
      comments: true
      list: true
      show-nav: true
  - scope:
      path: ""
      type: texturepacks
    values:
      comments: true
      list: true
      show-nav: true
      require:
        - texture-pack-manager
  - scope:
      path: ""
      type: shaders
    values:
      comments: true
      list: true
      show-nav: true
      require:
        - texture-pack-manager
        - boxcritters-shaders
  - scope:
      path: ""
      type: projects
    values:
      comments: true
      list: true
      show-nav: true
  - scope:
      path: ""
      type: servers
    values:
      comments: true
      list: true
      show-nav: true
  - scope:
      path: ""
      type: authors
    values:
      comments: true
      list: true
      show-nav: true
  - scope:
      path: ""
      type: posts
    values:
      comments: true
      list: true
      show-nav: true
  - scope:
      path: ""
      type: other
    values:
      comments: true
      list: true
      show-nav: true